# Generated by Django 4.2.10 on 2024-05-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCureIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_schedule',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doc_schedule',
            name='to_date',
            field=models.DateField(),
        ),
    ]
