# Generated by Django 5.0.3 on 2024-04-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="addressLine2",
            field=models.CharField(default=" ", max_length=254),
        ),
        migrations.AlterField(
            model_name="patientcreditcard",
            name="addressLine2",
            field=models.CharField(default=" ", max_length=254),
        ),
    ]
