# Generated by Django 5.0.3 on 2024-05-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0002_alter_appointments_patient_rec_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="schedule_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="weCureIt.doc_schedule",
            ),
        ),
    ]
