# Generated by Django 5.0.3 on 2024-04-03 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0003_alter_patient_addressline2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
