# Generated by Django 5.0.3 on 2024-04-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0004_appointments_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc_schedule",
            name="visiting_hours",
        ),
        migrations.AddField(
            model_name="doc_schedule",
            name="visiting_hours_end",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="doc_schedule",
            name="visiting_hours_start",
            field=models.TimeField(null=True),
        ),
    ]
