# Generated by Django 5.0.3 on 2024-04-04 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0005_remove_doc_schedule_visiting_hours_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc_schedule",
            name="facility_visiting",
        ),
        migrations.AddField(
            model_name="doc_schedule",
            name="facility_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="weCureIt.facility",
            ),
        ),
    ]
