# Generated by Django 4.2.11 on 2024-04-04 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weCureIt', '0005_alter_patient_addressline2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_pref', models.CharField(null=True)),
                ('facility_pref', models.CharField(null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weCureIt.patient')),
            ],
        ),
    ]
