# Generated by Django 5.0.3 on 2024-04-05 16:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weCureIt", "0006_remove_doc_schedule_facility_visiting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=254), size=None
            ),
        ),
    ]
