# Generated by Django 4.2.11 on 2024-04-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weCureIt', '0006_patientpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientpreference',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientpreference',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weCureIt.patient'),
        ),
    ]
