# Generated by Django 4.2.11 on 2024-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCureIt', '0007_remove_patientpreference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
