# Generated by Django 4.2.11 on 2024-04-04 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weCureIt', '0008_alter_facility_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), size=None),
        ),
    ]
