# Generated by Django 4.2.11 on 2024-04-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weCureIt', '0010_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientpreference',
            name='doctor_pref',
        ),
        migrations.RemoveField(
            model_name='patientpreference',
            name='facility_pref',
        ),
        migrations.AddField(
            model_name='patientpreference',
            name='doctor_pref_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientpreference',
            name='facility_pref_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patientpreference',
            name='patient_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weCureIt.patient'),
        ),
    ]
